import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";



export const metadata: Metadata = {
  title: "Job Board",
  description: "Generated by Job Board",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <NavBar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
